name: "Kopia"
description: "Fast and Secure Open-Source Backup Software"
version: "0.19.0"
slug: "kopia"
panel_icon: mdi:archive-sync
panel_admin: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

init: true
startup: "services"
ingress: false
ingress_port: 51515
apparmor: true
hassio_api: true
hassio_role: default
backup: "cold"
options:
  webui_password: "use_this_to_access_webui"
  repo_password: "use_this_when_creating_a_repository"
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  webui_password: password
  repo_password: password
  ssl: bool
  certfile: str
  keyfile: str
map:
  - type: addon_config
    read_only: false
    path: /app/config
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: ssl
ports:
  51515/tcp: 51515
ports_description:
  51515/tcp: the port at which the kopia web server will be available.
webui: "[PROTO:ssl]://[HOST]:[PORT:51515]"
watchdog: "[PROTO:ssl]://[HOST]:[PORT:51515]/repo"
host_network: true
environment:
  KOPIA_PASSWORD: "Mx9tvCWfOcy2"
  KOPIA_SERVER_CONTROL_PASSWORD: "Mx9tvCWfOcy2"
  KOPIA_CACHE_DIRECTORY: "/app/cache"
  KOPIA_CHECK_FOR_UPDATES: "false"
  KOPIA_CONFIG_PATH: "/app/config/repository.config"
  KOPIA_LOG_DIR: "/app/logs"
  KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: "false"
s6_overlay_stage2_exit: 0
url: "https://github.com/mautech05/ha-addons"